#file= open("file.txt","r")
#content= file.read()
#print(content)
#file.close()
f=open("file.txt","r")
print("file name:",f.name)
print("mode:",f.mode)
print("Is closed?",f.closed)
f.close()
print("Is closed?",f.closed)
